### ISSUE TITLE
Offensive module swapping stops working

### ISSUE THREAD

**Issue by Pitmairen** [hasirak/ProcessingGameProject#32]
Sometimes swapping of the offensive module stops working and the player gets stuck with a single weapon.

**Comment by Pitmairen** [comment]
It is caused by the same module being added more than once to the offensiveModules list.

**Comment by ghost** [comment]
Should be fixed now. Commit: 33d6d5835c951200fd01ebebe1ede843631e29f5
Reopen this issue if problem persists or reappears.
