### ISSUE TITLE
Game title suggestions

### ISSUE THREAD

**Issue by ghost** [hasirak/ProcessingGameProject#7]
Post your ideas for the game title.

**Comment by ghost** [comment]
Xeno Blaster 4000 (XB4K)

**Comment by alegro91** [comment]
Meteo Cruiser

**Comment by TMHolen95** [comment]
Shall we conclude with Xeno Blaster 4000, since that is the current game title? If so close this issue ;-)

**Comment by TMHolen95** [comment]
Closed
